spring.application.name=water-meter-service
spring.main.lazy-initialization=true
server.servlet.context-path=/
test.table.name=${TEST_TABLE_NAME:TestTable}
users.table.name=${USERS_TABLE_NAME:WaterMeterUsers}
tenants.table.name=${TENANTS_TABLE_NAME:WaterMeterTenants}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI:https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_vm19Xv95r}
logging.level.root=WARN
logging.level.com.vswitch.watermeter=INFO
logging.level.org.springframework=WARN
